# Generated by Django 5.0.2 on 2024-11-14 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="notes",
            old_name="tittel",
            new_name="title",
        ),
    ]
